ASR/Controllers/RoomController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ASR.Models;
using Microsoft.AspNetCore.Authorization;
using ASR.Data;

namespace ASR.Controllers
{
    public class RoomController : Controller
    {
        private readonly ASRContext _context;

        public RoomController(ASRContext context)
        {
            _context = context;
        }

        // GET: Rooms
        public async Task<IActionResult> Index()
        {
            return View(new RoomViewModel
            {
                Rooms = await _context.Room.ToListAsync(),
                StartTime = DateTime.Now.Date + new TimeSpan(9, 0, 0)
            });
        }

        // GET: Room/Availability
        [Authorize(Roles = Constants.StaffRole)]
        public async Task<IActionResult> Availability(RoomViewModel viewModel)
        {
            // gets all rooms for a given date
            var roomIDsForDate = _context.Slot.Where(x => x.StartTime.Date == viewModel.StartTime)
                .Select(x => x.RoomID)
                .ToList();

            // get the rooms that have been booked twice or more
            var excludeRooms = roomIDsForDate.GroupBy(x => x)
                .Where(g => g.Count() >= 2)
                .Select(x => x.Key);

            // get the rooms that are available
            var availableRooms = _context.Room.Where(x => !excludeRooms.Contains(x.RoomID));

            return View(await availableRooms.ToListAsync());
        }
    }
}

ASR/Controllers/SlotController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using ASR.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;
using ASR.Data;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ASR.Controllers
{
    public class SlotController : Controller
    {
        private readonly ASRContext _context;

        public SlotController(ASRContext context)
        {
            _context = context;
        }

        // GET: Slot
        public async Task<IActionResult> Index()
        {
            // get all staff users
            var staff = _context.ApplicationUser.Where(x => x.SchoolID.StartsWith('e'));

            // order slots by date and include staff and student relationships
            var slots = _context.Slot.Select(x => x)
                .OrderBy(x => x.StartTime)
                .Include(x => x.Student)
                .Include(x => x.Staff);

            return View(new SlotStaffViewModel
            {
                Slots = await slots.ToListAsync(),
                Staff = new SelectList(await staff.ToListAsync(), "SchoolID", "SchoolID"),
                StartTime = DateTime.Now.Date + new TimeSpan(9, 0, 0)
            });
        }

        // GET: Slot/Create
        [Authorize(Roles = Constants.StaffRole)]
        public async Task<IActionResult> Create()
        {
            var rooms = _context.Room.Select(x => x.RoomID);

            return View(new SlotRoomsViewModel
            {
                Rooms = new SelectList(await rooms.ToListAsync()),
                StartTime = DateTime.Now.Date + new TimeSpan(9, 0, 0)
            });
        }

        // POST: Slot/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = Constants.StaffRole)]
        public async Task<IActionResult> Create(SlotRoomsViewModel slotRoomsViewModel)
        {
            // get logged in user
            ApplicationUser currentUser = _context.ApplicationUser
                .FirstOrDefault(u => u.Email == HttpContext.User.Identity.Name);

            if (ModelState.IsValid)
            {
                var slot = new Slot
                {
                    StartTime = slotRoomsViewModel.StartTime,
                    RoomID = slotRoomsViewModel.RoomID,
                    StaffID = currentUser.Id,
                };

                _context.Add(slot);
                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }

            // re-fetch the rooms
            var rooms = _context.Room.Select(x => x.RoomID);
            slotRoomsViewModel.Rooms = new SelectList(await rooms.ToListAsync());

            return View(slotRoomsViewModel);
        }

        // POST: Slot/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = Constants.StudentRole)]
        public async Task<IActionResult> Book(string roomID, DateTime startTime)
        {
            var slot = _context.Slot.FirstOrDefault(s => s.RoomID == roomID && s.StartTime == startTime);

            // get current logged in user
            ApplicationUser currentUser = _context.ApplicationUser
                    .FirstOrDefault(u => u.Email == HttpContext.User.Identity.Name);

            // check if the student has booked the maximum slots for the given date
            var studentBookedMaxForDate = _context.Slot
                .FirstOrDefault(x => x.StartTime.Date == startTime.Date && x.StudentID == currentUser.Id) != null;

            if ((slot.StudentID == null) && (!studentBookedMaxForDate))
            {
                slot.StudentID = currentUser.Id;
            }
            else if (slot.StudentID == currentUser.Id)
            {
                slot.StudentID = null;
            }

            _context.Update(slot);

            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        // POST: Slot/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = Constants.StaffRole)]
        public async Task<IActionResult> Delete(string roomID, DateTime startTime)
        {
            var slot = _context.Slot.FirstOrDefault(s => s.RoomID == roomID && s.StartTime == startTime);

            if (slot.StudentID != null)
            {
                return RedirectToAction(nameof(Index));
            }

            _context.Remove(slot);

            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        // GET: Slot/Availability
        [Authorize(Roles = Constants.StudentRole)]
        public async Task<IActionResult> Availability(Slot slot, string staffID)
        {
            // get available slots for a given staff and date
            var availableSlots = _context.Slot.Where(x => x.Staff.SchoolID == staffID)
                .Where(x => x.StartTime.Date == slot.StartTime.Date)
                .Where(x => x.StudentID == null)
                .Include(s => s.Staff);

            return View(await availableSlots.ToListAsync());
        }

        // GET: Slot/Report
        [Authorize(Roles = Constants.StaffRole)]
        public async Task<IActionResult> Report()
        {
            // get current logged in user
            ApplicationUser staff = _context.ApplicationUser
                    .FirstOrDefault(u => u.Email == HttpContext.User.Identity.Name);

            // get all slots for the given user and date
            var slots = _context.Slot.Where(x => x.StaffID == staff.Id)
                .OrderBy(x => x.StartTime)
                .Include(x => x.Student);

            return View(await slots.ToListAsync());
        }
    }
}

ASR/Controllers/StaffController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ASR.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using ASR.Data;

namespace ASR.Controllers
{
    [Authorize(Roles = Constants.StaffRole)]
    public class StaffController : Controller
    {
        private readonly ASRContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public StaffController(ASRContext context,UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Staff
        public async Task<IActionResult> Index()
        {
            var staff = await _userManager.GetUsersInRoleAsync(Constants.StaffRole);
            return View(staff);
        }
    }
}

ASR/Controllers/StudentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ASR.Models;
using ASR.Data;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;

namespace ASR.Controllers
{
    [Authorize(Roles = Constants.StudentRole)]
    public class StudentController : Controller
    {
        private readonly ASRContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public StudentController(ASRContext context,UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Staff
        public async Task<IActionResult> Index()
        {
            var staff = await _userManager.GetUsersInRoleAsync(Constants.StudentRole);
            return View(staff);
        }
    }
}

ASR/Views/Shared/_Layout.cshtml
@using ASR.Data

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ASR</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/lib/bootstrap/scss/bootstrap.scss" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Love+Ya+Like+A+Sister" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body class="bg-light body-content">

    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-light bg-light-blue-solid">
            <a class="navbar-brand asr-font" asp-area="" asp-controller="Home" asp-action="Index">
                <img src="~/images/logo.png" width="60" height="60" class="d-inline-block align-content-center" alt="ASR">ASR
            </a>

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse justify-content-between" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">
                            Home <span class="sr-only">(current)</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Room" asp-action="Index">Rooms</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Slot" asp-action="Index">Slots</a>
                    </li>
                    @if (User.IsInRole(Constants.StudentRole))
                    {
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Student" asp-action="Index">Students</a>
                        </li>
                    }
                    @if (User.IsInRole(Constants.StaffRole))
                    {
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Staff" asp-action="Index">Staff</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Slot" asp-action="Report">Report</a>
                        </li>
                    }
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Home" asp-action="FAQ">FAQ</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Sitemap">Sitemap</a>
                    </li>
                </ul>

                <partial name="_LoginPartial" />
            </div>
        </nav>
    </div>

    <partial name="_CookieConsentPartial" />
    @RenderBody()
    <footer class="center-text text-sm pt-2">
        <div class="container">
            <div class="d-flex justify-content-center pt-4 text-sm center-text">
                <div class="col-md-4">
                    <ul class="list-unstyled">
                        <li>Testimonials</li>
                        <li>Sitemap</li>
                        <li>Newsletter</li>
                    </ul>
                </div>
                <div class="col-md-4">
                    <ul class="list-unstyled">
                        <li>Copyright</li>
                        <li>Terms of Use</li>
                        <li>Privacy Policy</li>
                    </ul>
                </div>
                <div class="col-md-4">
                    <ul class="list-unstyled">
                        <li>About Us</li>
                        <li>Careers</li>
                        <li>Contact</li>
                    </ul>
                </div>
            </div>
            <hr />
        </div>
        <p>&copy; 2019 - Aiden Garipoli &amp; Hayden Warmington</p>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>